### ISSUE TITLE
youtube-dl error

### ISSUE THREAD

**Issue by Anonymous78910** [pystardust/ytfzf#431]
ytfzf was working fine for me until yesterday. Now everytime I try to play something 
I am getting this error

> [ytdl_hook] ERROR: Signature extraction failed: Traceback (most recent call last):
> [ytdl_hook]   File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1348, in _decrypt_signature
> [ytdl_hook]     func = self._extract_signature_function(
> [ytdl_hook]   File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1262, in _extract_signature_function
> [ytdl_hook]     res = self._parse_sig_js(code)
> [ytdl_hook]   File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1331, in _parse_sig_js
> [ytdl_hook]     initial_function = jsi.extract_function(funcname)
> [ytdl_hook]   File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 245, in extract_function
> [ytdl_hook]     raise ExtractorError('Could not find JS function %r' % funcname)
> [ytdl_hook] youtube_dl.utils.ExtractorError: Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> [ytdl_hook]  (caused by ExtractorError("Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> [ytdl_hook] youtube-dl failed: unexpected error ocurred
> [ytdl_hook] It appears that your youtube-dl version is severely out of date.
> Failed to recognize file format.

I tried the python, apt packages nothing seems to work. youtube-dl --version = 2021.06.06

**Comment by Anonymous78910** [comment]
Looks like this is a youtube-dl issue. Many others are encountering this issue. Closing for now
