### ISSUE TITLE
Cant install videos

### ISSUE THREAD

**Issue by whoTryingToProgramming** [pystardust/ytfzf#665]
### Before Making This Post
* [ ] I have taken a look at both man pages, `ytfzf(1)` and `ytfzf(5)`

### What do you need help with?
When I try to install something by ytfzf i get this:

rvwork@rvwork-desktop:~$ ytfzf -T mpv
Search
> meet the engineer
Scraping YouTube (with https://invidious.nerdvpn.de) (meet the engineer, pg: 1)
[ytdl_hook] Traceback (most recent call last):
[ytdl_hook]   File "<frozen zipimport>", line 576, in _get_decompress_func
[ytdl_hook] ModuleNotFoundError: No module named 'zlib'
[ytdl_hook] 
[ytdl_hook] During handling of the above exception, another exception occurred:
[ytdl_hook] 
[ytdl_hook] Traceback (most recent call last):
[ytdl_hook]   File "<frozen zipimport>", line 624, in _get_data
[ytdl_hook]   File "<frozen zipimport>", line 579, in _get_decompress_func
[ytdl_hook] zipimport.ZipImportError: can't decompress data; zlib not available
[ytdl_hook] 
[ytdl_hook] During handling of the above exception, another exception occurred:
[ytdl_hook] 
[ytdl_hook] Traceback (most recent call last):
[ytdl_hook]   File "<frozen runpy>", line 159, in _get_module_details
[ytdl_hook]   File "<frozen zipimport>", line 195, in get_code
[ytdl_hook]   File "<frozen zipimport>", line 758, in _get_module_code
[ytdl_hook]   File "<frozen zipimport>", line 626, in _get_data
[ytdl_hook] zipimport.ZipImportError: can't decompress data; zlib not available
[ytdl_hook] 
[ytdl_hook] The above exception was the direct cause of the following exception:
[ytdl_hook] 
[ytdl_hook] Traceback (most recent call last):
[ytdl_hook]   File "<frozen runpy>", line 191, in _run_module_as_main
[ytdl_hook]   File "<frozen runpy>", line 240, in _get_main_module_details
[ytdl_hook]   File "<frozen runpy>", line 161, in _get_module_details
[ytdl_hook] ImportError: can't decompress data; zlib not available 
[ytdl_hook] youtube-dl failed: unexpected error occurred 
Failed to recognize file format.

Please help

**Comment by Euro20179** [comment]
to me it seems you need to install the zlib python package, but if you have then I have no idea.

**Comment by tabletseeker** [comment]
Updated and working ytfzf project here:
https://github.com/tabletseeker/ytfzf_prime
